// Common IANA timezones for the organization settings select.
export const COMMON_TIMEZONES = [
  { value: "UTC", label: "UTC" },
  { value: "America/New_York", label: "Eastern Time — New York" },
  { value: "America/Chicago", label: "Central Time — Chicago" },
  { value: "America/Denver", label: "Mountain Time — Denver" },
  { value: "America/Phoenix", label: "Mountain Time — Phoenix (no DST)" },
  { value: "America/Los_Angeles", label: "Pacific Time — Los Angeles" },
  { value: "America/Anchorage", label: "Alaska — Anchorage" },
  { value: "Pacific/Honolulu", label: "Hawaii — Honolulu" },
  { value: "America/Toronto", label: "Canada — Toronto" },
  { value: "America/Vancouver", label: "Canada — Vancouver" },
  { value: "America/Mexico_City", label: "Mexico — Mexico City" },
  { value: "America/Bogota", label: "Colombia — Bogotá" },
  { value: "America/Lima", label: "Peru — Lima" },
  { value: "America/Sao_Paulo", label: "Brazil — São Paulo" },
  { value: "America/Argentina/Buenos_Aires", label: "Argentina — Buenos Aires" },
  { value: "Europe/London", label: "United Kingdom — London" },
  { value: "Europe/Dublin", label: "Ireland — Dublin" },
  { value: "Europe/Lisbon", label: "Portugal — Lisbon" },
  { value: "Europe/Paris", label: "Central Europe — Paris" },
  { value: "Europe/Berlin", label: "Central Europe — Berlin" },
  { value: "Europe/Madrid", label: "Spain — Madrid" },
  { value: "Europe/Rome", label: "Italy — Rome" },
  { value: "Europe/Amsterdam", label: "Netherlands — Amsterdam" },
  { value: "Europe/Stockholm", label: "Sweden — Stockholm" },
  { value: "Europe/Warsaw", label: "Poland — Warsaw" },
  { value: "Europe/Athens", label: "Greece — Athens" },
  { value: "Europe/Kyiv", label: "Ukraine — Kyiv" },
  { value: "Europe/Istanbul", label: "Türkiye — Istanbul" },
  { value: "Europe/Moscow", label: "Russia — Moscow" },
  { value: "Africa/Lagos", label: "Nigeria — Lagos" },
  { value: "Africa/Accra", label: "Ghana — Accra" },
  { value: "Africa/Cairo", label: "Egypt — Cairo" },
  { value: "Africa/Nairobi", label: "Kenya — Nairobi" },
  { value: "Africa/Johannesburg", label: "South Africa — Johannesburg" },
  { value: "Asia/Jerusalem", label: "Israel — Jerusalem" },
  { value: "Asia/Dubai", label: "UAE — Dubai" },
  { value: "Asia/Karachi", label: "Pakistan — Karachi" },
  { value: "Asia/Kolkata", label: "India — Kolkata" },
  { value: "Asia/Dhaka", label: "Bangladesh — Dhaka" },
  { value: "Asia/Bangkok", label: "Thailand — Bangkok" },
  { value: "Asia/Jakarta", label: "Indonesia — Jakarta" },
  { value: "Asia/Singapore", label: "Singapore" },
  { value: "Asia/Manila", label: "Philippines — Manila" },
  { value: "Asia/Hong_Kong", label: "Hong Kong" },
  { value: "Asia/Shanghai", label: "China — Shanghai" },
  { value: "Asia/Seoul", label: "South Korea — Seoul" },
  { value: "Asia/Tokyo", label: "Japan — Tokyo" },
  { value: "Australia/Perth", label: "Australia — Perth" },
  { value: "Australia/Adelaide", label: "Australia — Adelaide" },
  { value: "Australia/Brisbane", label: "Australia — Brisbane" },
  { value: "Australia/Sydney", label: "Australia — Sydney" },
  { value: "Pacific/Auckland", label: "New Zealand — Auckland" },
  { value: "Pacific/Fiji", label: "Fiji" },
] as const;
